/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from '@routes/__root.tsx'
import { Route as PathlessLayoutRouteImport } from '@routes/_pathlessLayout'
import { Route as SiginRouteRouteImport } from '@routes/sigin/route'
import { Route as SiginSignInRouteImport } from '@routes/sigin/SignIn'
import { Route as ShowUiShowUIRouteImport } from '@routes/show-ui/ShowUI'
import { Route as HomeHomeRouteImport } from '@routes/home/Home'
import { Route as PacksAddPackRouteRouteImport } from '@routes/packs/addPack/route'
import { Route as PacksPacksRouteRouteImport } from '@routes/packs/showPacks/route'
import { Route as PacksAddPackAddPackRouteImport } from '@routes/packs/addPack/AddPack'
import { Route as PacksPacksPacksRouteImport } from '@routes/packs/showPacks/ShowPacks'

const PathlessLayoutRoute = PathlessLayoutRouteImport.update({
  id: '/_pathlessLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const SiginRouteRoute = SiginRouteRouteImport.update({
  id: '/sigin',
  path: '/sigin',
  getParentRoute: () => rootRouteImport,
} as any)
const SiginSignInRoute = SiginSignInRouteImport.update({
  id: '/SignIn',
  path: '/SignIn',
  getParentRoute: () => SiginRouteRoute,
} as any)
const ShowUiShowUIRoute = ShowUiShowUIRouteImport.update({
  id: '/show-ui/ShowUI',
  path: '/show-ui/ShowUI',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeHomeRoute = HomeHomeRouteImport.update({
  id: '/home/Home',
  path: '/home/Home',
  getParentRoute: () => rootRouteImport,
} as any)
const PacksAddPackRouteRoute = PacksAddPackRouteRouteImport.update({
  id: '/packs/addPack',
  path: '/packs/addPack',
  getParentRoute: () => rootRouteImport,
} as any)
const PacksPacksRouteRoute = PacksPacksRouteRouteImport.update({
  id: '/packs/Packs',
  path: '/packs/Packs',
  getParentRoute: () => rootRouteImport,
} as any)
const PacksAddPackAddPackRoute = PacksAddPackAddPackRouteImport.update({
  id: '/AddPack',
  path: '/AddPack',
  getParentRoute: () => PacksAddPackRouteRoute,
} as any)
const PacksPacksPacksRoute = PacksPacksPacksRouteImport.update({
  id: '/Packs',
  path: '/Packs',
  getParentRoute: () => PacksPacksRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/sigin': typeof SiginRouteRouteWithChildren
  '/packs/Packs': typeof PacksPacksRouteRouteWithChildren
  '/packs/addPack': typeof PacksAddPackRouteRouteWithChildren
  '/home/Home': typeof HomeHomeRoute
  '/show-ui/ShowUI': typeof ShowUiShowUIRoute
  '/sigin/SignIn': typeof SiginSignInRoute
  '/packs/Packs/Packs': typeof PacksPacksPacksRoute
  '/packs/addPack/AddPack': typeof PacksAddPackAddPackRoute
}
export interface FileRoutesByTo {
  '/sigin': typeof SiginRouteRouteWithChildren
  '/packs/Packs': typeof PacksPacksRouteRouteWithChildren
  '/packs/addPack': typeof PacksAddPackRouteRouteWithChildren
  '/home/Home': typeof HomeHomeRoute
  '/show-ui/ShowUI': typeof ShowUiShowUIRoute
  '/sigin/SignIn': typeof SiginSignInRoute
  '/packs/Packs/Packs': typeof PacksPacksPacksRoute
  '/packs/addPack/AddPack': typeof PacksAddPackAddPackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/sigin': typeof SiginRouteRouteWithChildren
  '/_pathlessLayout': typeof PathlessLayoutRoute
  '/packs/Packs': typeof PacksPacksRouteRouteWithChildren
  '/packs/addPack': typeof PacksAddPackRouteRouteWithChildren
  '/home/Home': typeof HomeHomeRoute
  '/show-ui/ShowUI': typeof ShowUiShowUIRoute
  '/sigin/SignIn': typeof SiginSignInRoute
  '/packs/Packs/Packs': typeof PacksPacksPacksRoute
  '/packs/addPack/AddPack': typeof PacksAddPackAddPackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/sigin'
    | '/packs/Packs'
    | '/packs/addPack'
    | '/home/Home'
    | '/show-ui/ShowUI'
    | '/sigin/SignIn'
    | '/packs/Packs/Packs'
    | '/packs/addPack/AddPack'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/sigin'
    | '/packs/Packs'
    | '/packs/addPack'
    | '/home/Home'
    | '/show-ui/ShowUI'
    | '/sigin/SignIn'
    | '/packs/Packs/Packs'
    | '/packs/addPack/AddPack'
  id:
    | '__root__'
    | '/sigin'
    | '/_pathlessLayout'
    | '/packs/Packs'
    | '/packs/addPack'
    | '/home/Home'
    | '/show-ui/ShowUI'
    | '/sigin/SignIn'
    | '/packs/Packs/Packs'
    | '/packs/addPack/AddPack'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SiginRouteRoute: typeof SiginRouteRouteWithChildren
  PathlessLayoutRoute: typeof PathlessLayoutRoute
  PacksPacksRouteRoute: typeof PacksPacksRouteRouteWithChildren
  PacksAddPackRouteRoute: typeof PacksAddPackRouteRouteWithChildren
  HomeHomeRoute: typeof HomeHomeRoute
  ShowUiShowUIRoute: typeof ShowUiShowUIRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_pathlessLayout': {
      id: '/_pathlessLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PathlessLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sigin': {
      id: '/sigin'
      path: '/sigin'
      fullPath: '/sigin'
      preLoaderRoute: typeof SiginRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sigin/SignIn': {
      id: '/sigin/SignIn'
      path: '/SignIn'
      fullPath: '/sigin/SignIn'
      preLoaderRoute: typeof SiginSignInRouteImport
      parentRoute: typeof SiginRouteRoute
    }
    '/show-ui/ShowUI': {
      id: '/show-ui/ShowUI'
      path: '/show-ui/ShowUI'
      fullPath: '/show-ui/ShowUI'
      preLoaderRoute: typeof ShowUiShowUIRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/Home': {
      id: '/home/Home'
      path: '/home/Home'
      fullPath: '/home/Home'
      preLoaderRoute: typeof HomeHomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packs/addPack': {
      id: '/packs/addPack'
      path: '/packs/addPack'
      fullPath: '/packs/addPack'
      preLoaderRoute: typeof PacksAddPackRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packs/Packs': {
      id: '/packs/Packs'
      path: '/packs/Packs'
      fullPath: '/packs/Packs'
      preLoaderRoute: typeof PacksPacksRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packs/addPack/AddPack': {
      id: '/packs/addPack/AddPack'
      path: '/AddPack'
      fullPath: '/packs/addPack/AddPack'
      preLoaderRoute: typeof PacksAddPackAddPackRouteImport
      parentRoute: typeof PacksAddPackRouteRoute
    }
    '/packs/Packs/Packs': {
      id: '/packs/Packs/Packs'
      path: '/Packs'
      fullPath: '/packs/Packs/Packs'
      preLoaderRoute: typeof PacksPacksPacksRouteImport
      parentRoute: typeof PacksPacksRouteRoute
    }
  }
}

interface SiginRouteRouteChildren {
  SiginSignInRoute: typeof SiginSignInRoute
}

const SiginRouteRouteChildren: SiginRouteRouteChildren = {
  SiginSignInRoute: SiginSignInRoute,
}

const SiginRouteRouteWithChildren = SiginRouteRoute._addFileChildren(
  SiginRouteRouteChildren,
)

interface PacksPacksRouteRouteChildren {
  PacksPacksPacksRoute: typeof PacksPacksPacksRoute
}

const PacksPacksRouteRouteChildren: PacksPacksRouteRouteChildren = {
  PacksPacksPacksRoute: PacksPacksPacksRoute,
}

const PacksPacksRouteRouteWithChildren = PacksPacksRouteRoute._addFileChildren(
  PacksPacksRouteRouteChildren,
)

interface PacksAddPackRouteRouteChildren {
  PacksAddPackAddPackRoute: typeof PacksAddPackAddPackRoute
}

const PacksAddPackRouteRouteChildren: PacksAddPackRouteRouteChildren = {
  PacksAddPackAddPackRoute: PacksAddPackAddPackRoute,
}

const PacksAddPackRouteRouteWithChildren =
  PacksAddPackRouteRoute._addFileChildren(PacksAddPackRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  SiginRouteRoute: SiginRouteRouteWithChildren,
  PathlessLayoutRoute: PathlessLayoutRoute,
  PacksPacksRouteRoute: PacksPacksRouteRouteWithChildren,
  PacksAddPackRouteRoute: PacksAddPackRouteRouteWithChildren,
  HomeHomeRoute: HomeHomeRoute,
  ShowUiShowUIRoute: ShowUiShowUIRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
