/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PathlessLayoutRouteImport } from './routes/_pathlessLayout'
import { Route as SiginRouteRouteImport } from './routes/sigin/route'
import { Route as SiginSignInRouteImport } from './routes/sigin/SignIn'
import { Route as ShowUiShowUIRouteImport } from './routes/show-ui/ShowUI'
import { Route as PacksShowPacksShowPacksRouteImport } from './routes/packs/showPacks/ShowPacks'
import { Route as PacksAddPackAddPackRouteImport } from './routes/packs/addPack/AddPack'

const PathlessLayoutRoute = PathlessLayoutRouteImport.update({
  id: '/_pathlessLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const SiginRouteRoute = SiginRouteRouteImport.update({
  id: '/sigin',
  path: '/sigin',
  getParentRoute: () => rootRouteImport,
} as any)
const SiginSignInRoute = SiginSignInRouteImport.update({
  id: '/SignIn',
  path: '/SignIn',
  getParentRoute: () => SiginRouteRoute,
} as any)
const ShowUiShowUIRoute = ShowUiShowUIRouteImport.update({
  id: '/show-ui/ShowUI',
  path: '/show-ui/ShowUI',
  getParentRoute: () => rootRouteImport,
} as any)
const PacksShowPacksShowPacksRoute = PacksShowPacksShowPacksRouteImport.update({
  id: '/packs/showPacks/ShowPacks',
  path: '/packs/showPacks/ShowPacks',
  getParentRoute: () => rootRouteImport,
} as any)
const PacksAddPackAddPackRoute = PacksAddPackAddPackRouteImport.update({
  id: '/packs/addPack/AddPack',
  path: '/packs/addPack/AddPack',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/sigin': typeof SiginRouteRouteWithChildren
  '/show-ui/ShowUI': typeof ShowUiShowUIRoute
  '/sigin/SignIn': typeof SiginSignInRoute
  '/packs/addPack/AddPack': typeof PacksAddPackAddPackRoute
  '/packs/showPacks/ShowPacks': typeof PacksShowPacksShowPacksRoute
}
export interface FileRoutesByTo {
  '/sigin': typeof SiginRouteRouteWithChildren
  '/show-ui/ShowUI': typeof ShowUiShowUIRoute
  '/sigin/SignIn': typeof SiginSignInRoute
  '/packs/addPack/AddPack': typeof PacksAddPackAddPackRoute
  '/packs/showPacks/ShowPacks': typeof PacksShowPacksShowPacksRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/sigin': typeof SiginRouteRouteWithChildren
  '/_pathlessLayout': typeof PathlessLayoutRoute
  '/show-ui/ShowUI': typeof ShowUiShowUIRoute
  '/sigin/SignIn': typeof SiginSignInRoute
  '/packs/addPack/AddPack': typeof PacksAddPackAddPackRoute
  '/packs/showPacks/ShowPacks': typeof PacksShowPacksShowPacksRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/sigin'
    | '/show-ui/ShowUI'
    | '/sigin/SignIn'
    | '/packs/addPack/AddPack'
    | '/packs/showPacks/ShowPacks'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/sigin'
    | '/show-ui/ShowUI'
    | '/sigin/SignIn'
    | '/packs/addPack/AddPack'
    | '/packs/showPacks/ShowPacks'
  id:
    | '__root__'
    | '/sigin'
    | '/_pathlessLayout'
    | '/show-ui/ShowUI'
    | '/sigin/SignIn'
    | '/packs/addPack/AddPack'
    | '/packs/showPacks/ShowPacks'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SiginRouteRoute: typeof SiginRouteRouteWithChildren
  PathlessLayoutRoute: typeof PathlessLayoutRoute
  ShowUiShowUIRoute: typeof ShowUiShowUIRoute
  PacksAddPackAddPackRoute: typeof PacksAddPackAddPackRoute
  PacksShowPacksShowPacksRoute: typeof PacksShowPacksShowPacksRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_pathlessLayout': {
      id: '/_pathlessLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PathlessLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sigin': {
      id: '/sigin'
      path: '/sigin'
      fullPath: '/sigin'
      preLoaderRoute: typeof SiginRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sigin/SignIn': {
      id: '/sigin/SignIn'
      path: '/SignIn'
      fullPath: '/sigin/SignIn'
      preLoaderRoute: typeof SiginSignInRouteImport
      parentRoute: typeof SiginRouteRoute
    }
    '/show-ui/ShowUI': {
      id: '/show-ui/ShowUI'
      path: '/show-ui/ShowUI'
      fullPath: '/show-ui/ShowUI'
      preLoaderRoute: typeof ShowUiShowUIRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packs/showPacks/ShowPacks': {
      id: '/packs/showPacks/ShowPacks'
      path: '/packs/showPacks/ShowPacks'
      fullPath: '/packs/showPacks/ShowPacks'
      preLoaderRoute: typeof PacksShowPacksShowPacksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packs/addPack/AddPack': {
      id: '/packs/addPack/AddPack'
      path: '/packs/addPack/AddPack'
      fullPath: '/packs/addPack/AddPack'
      preLoaderRoute: typeof PacksAddPackAddPackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SiginRouteRouteChildren {
  SiginSignInRoute: typeof SiginSignInRoute
}

const SiginRouteRouteChildren: SiginRouteRouteChildren = {
  SiginSignInRoute: SiginSignInRoute,
}

const SiginRouteRouteWithChildren = SiginRouteRoute._addFileChildren(
  SiginRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  SiginRouteRoute: SiginRouteRouteWithChildren,
  PathlessLayoutRoute: PathlessLayoutRoute,
  ShowUiShowUIRoute: ShowUiShowUIRoute,
  PacksAddPackAddPackRoute: PacksAddPackAddPackRoute,
  PacksShowPacksShowPacksRoute: PacksShowPacksShowPacksRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
