/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PathlessLayoutRouteImport } from './routes/_pathlessLayout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SignInIndexRouteImport } from './routes/sign-in/index'
import { Route as PacksIndexRouteImport } from './routes/packs/index'
import { Route as ShowUiShowUIRouteImport } from './routes/show-ui/ShowUI'
import { Route as PacksAddPackAddPackRouteImport } from './routes/packs/addPack/AddPack'

const PathlessLayoutRoute = PathlessLayoutRouteImport.update({
  id: '/_pathlessLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInIndexRoute = SignInIndexRouteImport.update({
  id: '/sign-in/',
  path: '/sign-in/',
  getParentRoute: () => rootRouteImport,
} as any)
const PacksIndexRoute = PacksIndexRouteImport.update({
  id: '/packs/',
  path: '/packs/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowUiShowUIRoute = ShowUiShowUIRouteImport.update({
  id: '/show-ui/ShowUI',
  path: '/show-ui/ShowUI',
  getParentRoute: () => rootRouteImport,
} as any)
const PacksAddPackAddPackRoute = PacksAddPackAddPackRouteImport.update({
  id: '/packs/addPack/AddPack',
  path: '/packs/addPack/AddPack',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/show-ui/ShowUI': typeof ShowUiShowUIRoute
  '/packs': typeof PacksIndexRoute
  '/sign-in': typeof SignInIndexRoute
  '/packs/addPack/AddPack': typeof PacksAddPackAddPackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/show-ui/ShowUI': typeof ShowUiShowUIRoute
  '/packs': typeof PacksIndexRoute
  '/sign-in': typeof SignInIndexRoute
  '/packs/addPack/AddPack': typeof PacksAddPackAddPackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_pathlessLayout': typeof PathlessLayoutRoute
  '/show-ui/ShowUI': typeof ShowUiShowUIRoute
  '/packs/': typeof PacksIndexRoute
  '/sign-in/': typeof SignInIndexRoute
  '/packs/addPack/AddPack': typeof PacksAddPackAddPackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/show-ui/ShowUI'
    | '/packs'
    | '/sign-in'
    | '/packs/addPack/AddPack'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/show-ui/ShowUI' | '/packs' | '/sign-in' | '/packs/addPack/AddPack'
  id:
    | '__root__'
    | '/'
    | '/_pathlessLayout'
    | '/show-ui/ShowUI'
    | '/packs/'
    | '/sign-in/'
    | '/packs/addPack/AddPack'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PathlessLayoutRoute: typeof PathlessLayoutRoute
  ShowUiShowUIRoute: typeof ShowUiShowUIRoute
  PacksIndexRoute: typeof PacksIndexRoute
  SignInIndexRoute: typeof SignInIndexRoute
  PacksAddPackAddPackRoute: typeof PacksAddPackAddPackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_pathlessLayout': {
      id: '/_pathlessLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PathlessLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in/': {
      id: '/sign-in/'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packs/': {
      id: '/packs/'
      path: '/packs'
      fullPath: '/packs'
      preLoaderRoute: typeof PacksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/show-ui/ShowUI': {
      id: '/show-ui/ShowUI'
      path: '/show-ui/ShowUI'
      fullPath: '/show-ui/ShowUI'
      preLoaderRoute: typeof ShowUiShowUIRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packs/addPack/AddPack': {
      id: '/packs/addPack/AddPack'
      path: '/packs/addPack/AddPack'
      fullPath: '/packs/addPack/AddPack'
      preLoaderRoute: typeof PacksAddPackAddPackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PathlessLayoutRoute: PathlessLayoutRoute,
  ShowUiShowUIRoute: ShowUiShowUIRoute,
  PacksIndexRoute: PacksIndexRoute,
  SignInIndexRoute: SignInIndexRoute,
  PacksAddPackAddPackRoute: PacksAddPackAddPackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
