/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createRootRoute } from '@tanstack/react-router'

import { Route as PathlessLayoutRouteImport } from './routes/_pathlessLayout'
import { Route as HomeHomeRouteImport } from './routes/home/Home'

const rootRouteImport = createRootRoute()

const PathlessLayoutRoute = PathlessLayoutRouteImport.update({
  id: '/_pathlessLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeHomeRoute = HomeHomeRouteImport.update({
  id: '/home/Home',
  path: '/home/Home',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/home/Home': typeof HomeHomeRoute
}
export interface FileRoutesByTo {
  '/home/Home': typeof HomeHomeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_pathlessLayout': typeof PathlessLayoutRoute
  '/home/Home': typeof HomeHomeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/home/Home'
  fileRoutesByTo: FileRoutesByTo
  to: '/home/Home'
  id: '__root__' | '/_pathlessLayout' | '/home/Home'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PathlessLayoutRoute: typeof PathlessLayoutRoute
  HomeHomeRoute: typeof HomeHomeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_pathlessLayout': {
      id: '/_pathlessLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PathlessLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/Home': {
      id: '/home/Home'
      path: '/home/Home'
      fullPath: '/home/Home'
      preLoaderRoute: typeof HomeHomeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  PathlessLayoutRoute: PathlessLayoutRoute,
  HomeHomeRoute: HomeHomeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
